Add navbar admin + styte and link
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #128
Opened 2022-05-03 14:49 UTC by SkeidoK

2022-05-03 15:09 UTC, VanTej commented on src/View/Includes/_navbar_admin.html.twig
> +				<a class="nav-link text-light" href="#contact">Contact</a>
peut être pas besoin du lien contact

2022-05-03 20:18 UTC, SkeidoK commented on src/View/Includes/_navbar_admin.html.twig
> +				<a class="nav-link text-light" href="#contact">Contact</a>
Exact je l'enleve :)

2022-05-03 21:25 UTC, sblondeau requested changes

2022-05-03 21:25 UTC, sblondeau commented on src/View/Admin/Member/edit.html.twig
> +{% include 'Includes/_navbar_admin.html.twig' %}
du coup fait direct ton layoutAdmin dans cette PR, tu y inclus ta navbar_admin et tu enlèves ces block header qui deviennent inutile (en pensant cependant à modif les extends pour ces fichiers)

2022-05-04 07:21 UTC, sblondeau requested changes

2022-05-04 07:21 UTC, sblondeau commented on src/View/Admin/Workshop/index.html.twig
> +{% include 'Includes/_navbar_admin.html.twig' %}
et donc ne fais plus d'include de la navbar admin vu que c'est fait dans le layout_admin, c'était tout l'intéret ;-)

2022-05-04 08:22 UTC, sblondeau approved these changes

2022-05-04 08:22 UTC, merged