S03 us23 member delete
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #129
Opened 2022-05-03 15:06 UTC by VanTej

2022-05-03 20:09 UTC, SkeidoK approved these changes

2022-05-03 20:09 UTC, SkeidoK commented on src/View/Admin/Member/index.html.twig
> +							<button class="btn my-1" onSubmit="confirm('Etes-vous sûr de vouloir supprimer ce membre ?')">Supprimer</button>
Tu as mis deux fois la même chose sur deux balises differentes c'est normal?

2022-05-04 08:23 UTC, sblondeau requested changes

2022-05-04 08:23 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
> +							<button class="btn my-1" onSubmit="confirm('Etes-vous sûr de vouloir supprimer ce membre ?')">Supprimer</button>
+1 à enlever sur le button

2022-05-04 08:46 UTC, sblondeau approved these changes

2022-05-04 08:49 UTC, merged