S03 us9 editevent
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #154
Opened 2022-05-04 14:39 UTC by DangirasH

2022-05-04 14:41 UTC, SkeidoK approved these changes

2022-05-04 14:41 UTC, SkeidoK submitted a review, later dismissed

2022-05-04 15:02 UTC, sblondeau requested changes
index/show/edit sur la meme PR
validation pas là...
_edit à renommer en edit
a dans les button...
en fait plus d'erreur que je t'ai déjà corrigé, donc pb de branche, à recommencer, je veux une PR avec uniquement l'edit d'event

2022-05-05 09:15 UTC, sblondeau requested changes

2022-05-05 09:15 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +    public function index(): string
non index et show sont tjs de trop ici, je ne dois avoir que le code pour l'edit

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +	<input type="name" value="{{ event.date }}" name="date" id="date">
input type date

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +	<input type="text" value="{{ event.image_link }}" name="image_link" id="image_link">
input type url

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +	<input type="text" value="{{ event.description }}" name="description" id="description">
textarea plutot ?

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +	<button class="btn w-25 my-2 align-self-center">Envoi</button>
le w-25 me semble etrange, normalement en boostrap ton bouton a les classes btn ET btn-laCouleur, par ex btn-primary

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/_show.html.twig
> +{% endblock %}
le show est je pense inutile, à retirer (et dans tous les cas il n'a pas a etre dans cette PR)

2022-05-05 09:15 UTC, sblondeau commented on src/View/Admin/Event/index.html.twig
> +							<button class="btn my-1">Supprimer</button>
"btn btn-danger" par ex

2022-05-05 10:15 UTC, sblondeau approved these changes

2022-05-05 11:51 UTC, sblondeau commented
passe pas les check de github Action

2022-05-05 12:25 UTC, DangirasH commented
sans blague

2022-05-05 12:27 UTC, closed without merging