structure/style contact + contrôle, validation et route finis
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #156
Opened 2022-05-04 15:07 UTC by TheV2Maker

2022-05-04 15:20 UTC, SkeidoK submitted a review, later dismissed

2022-05-04 21:24 UTC, sblondeau requested changes

2022-05-04 21:24 UTC, sblondeau commented on src/Controller/ItemController.php
> +        }$id);
y a un pb d'accolade là ?

2022-05-04 21:24 UTC, sblondeau commented on src/View/Contact/contactEmail.html.twig
> +			{{ contact.name }}</div>
tu n'as pas de name mais un firstname et un lastname

2022-05-05 09:17 UTC, sblondeau approved these changes

2022-05-05 10:14 UTC, merged