S04 u sfix contact
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #189
Opened 2022-05-10 10:16 UTC by TheV2Maker

2022-05-10 11:50 UTC, DangirasH submitted a review, later dismissed

2022-05-10 12:02 UTC, sblondeau requested changes
image trop grosse ! pas plus de 100ko

2022-05-11 08:39 UTC, DangirasH approved these changes

2022-05-11 08:54 UTC, sblondeau approved these changes

2022-05-11 08:54 UTC, merged