S01 us12
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #23
Opened 2022-04-20 15:16 UTC by DangirasH

2022-04-20 15:19 UTC, SkeidoK commented
Attention aux nomages des photos.

2022-04-20 15:23 UTC, SkeidoK commented
OK pour moi!

2022-04-21 13:57 UTC, sblondeau requested changes
tu ne te sers pas de calendar4.svg, tu as copié/collé direct le svg, donc pas la peine d'enregistrer le fichier svg dans images

2022-04-21 15:14 UTC, sblondeau submitted a review, later dismissed

2022-04-22 06:51 UTC, SkeidoK submitted a review, later dismissed

2022-04-22 07:36 UTC, SkeidoK submitted a review, later dismissed

2022-04-22 08:11 UTC, sblondeau requested changes
j'avais pas fait attention à ta gestion des images, mais ça ne va pas. Les liens vers les images en base de données vont à terme pointer vers de images uploadées par l'administrateur. Donc elles devront se trouver dans un dossier public/uploads mais ne devront pas être versionnées.
Pour le moment, tant qu'on ne gère pas l'upload, c'est plus simple si tu créés une image "placeholder" (dans assets/images cette fois) que tu affiches si l'event n'a pas d'image, et tu enlèves les autres images de assets/images et de la base de donnée

2022-04-22 08:50 UTC, sblondeau approved these changes

2022-04-22 08:50 UTC, merged