Us01 s1
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #24
Opened 2022-04-20 15:30 UTC by TheV2Maker

2022-04-21 12:04 UTC, VanTej commented
ok pour moi

2022-04-21 14:00 UTC, sblondeau requested changes
l'image du logo est bien trop grosse, tu peux la réduire pour qu'elle fasse pas plus de 100ko

2022-04-21 14:25 UTC, VanTej commented on src/View/Includes/_navbar.html.twig
> +                <a class="nav-link" href="#event">Evènements</a>
sur le pc aucun soucis d'indentation

2022-04-21 15:15 UTC, sblondeau submitted a review, later dismissed

2022-04-22 07:28 UTC, SkeidoK submitted a review, later dismissed

2022-04-22 07:37 UTC, DangirasH approved these changes

2022-04-22 08:12 UTC, merged