So2 us fix04
WildCodeSchool/2022-03-php-orleans-project-kevrenn pull request #57
Opened 2022-04-27 09:37 UTC by DangirasH

Fixed all fix requirments and added variables for titles

2022-04-27 10:34 UTC, sblondeau requested changes

2022-04-27 10:34 UTC, sblondeau commented on public/assets/css/style.css
> +    --title-sizeh3: 26px;
mieux de travailler en rem

après bootstrap possède des classes pour les tailles de titre ou de police, qui peuvent aussi etre utilisées ;-)

2022-04-28 09:36 UTC, SkeidoK submitted a review, later dismissed

2022-04-28 10:00 UTC, sblondeau requested changes

2022-04-28 15:34 UTC, sblondeau submitted a review, later dismissed

2022-04-29 07:25 UTC, merged